### ISSUE TITLE
Provide greater color clarity

### ISSUE THREAD

**Issue by kauffj** [lbryio/color#3]
Many of the colors simply have five versions.

Do we actually need and always use all five?

Can we name them something that gives a better implication of when to use them than just one to five?

Inspired by https://github.com/lbryio/internal-apis/issues/733

**Comment by NetOperatorWibby** [comment]
Yes, we do need five. Often, we'll have something like `rgba($black, 0.3)` when that could be `$lbry-gray-2`. Having a single color limits what we could do with design. If you look at other styleguides, they are the same way.

You cannot expect every project to use colors in the same way.

**Comment by DEBSUBHRO** [comment]
I wanna do this.

**Comment by tzarebczan** [comment]
I don't think there's anything to do here, closing. But thank you!
